dynamic swerve drive ratios
HHS-Team670/MustangLib pull request #40
Opened 2023-03-18 22:30 UTC by arghunter

Ability to change swerve ratios based on mac address

2023-03-23 08:02 UTC, adias408 requested changes

2023-03-23 08:02 UTC, adias408 commented on constants/SwerveConfig.java
> +            int frontLeftModuleDriveMotor, int frontLeftModuleSteerMotor, int frontLeftModuleSteerEncoder,
This is another PR where we're mixing formatting changes with actual changes, which makes it very hard to figure out what's actually materially changed. Let's please stop doing this.

2023-03-23 08:02 UTC, adias408 commented on constants/SwerveConfig.java
> +    public GearRatio SWERVE_MODULE_CONFIGURATION;
why not call it SWERVE_MODULE_GEAR_RATIO if that's what it is? Configuration is one of those words that doesn't convey any meaning by itself.

2023-03-24 16:39 UTC, arghunter commented on constants/SwerveConfig.java
> +            int frontLeftModuleDriveMotor, int frontLeftModuleSteerMotor, int frontLeftModuleSteerEncoder,
My computer keeps auto formatting everything in a incredibly stupid way. Let me figure how to turn it off

2023-03-26 21:56 UTC, merged